name: toolship
version: 0.0.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
description: Package description here.
requirements:
- python ^3.5
- PySide2 ^5.15.2
- yubikey-manager ^4.0.5
- nr.optional ^0.1.1
- pynput ^1.7.3
