name: toolship-yubikey
version: 0.0.0
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
modulename: toolship.yubikey
description: Package description here.
requirements:
- toolship-core ~0.0.0
- PySide2 ^5.15.2
- python ^3.5
- yubikey-manager ^4.0.5
